ssh_user = "ubuntu"
gpg_path = "/usr/share/keyrings/mongodb-server-7.0.gpg"
ssh_key_path = "~/.ssh/id_rsa.pub"
project_path = ""
app_image = ""
google_maps_api_key = ""
github_user = ""
github_token = ""
